# Generated by Django 3.0 on 2020-08-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=30)),
                ('e_contact', models.IntegerField(unique=True)),
                ('e_salary', models.FloatField()),
            ],
        ),
    ]
